### ISSUE TITLE
crash_2020-07-27_09-47-08

### ISSUE THREAD

**Issue by FPS-86** [d3xter-dev/dayz-class-selection#1]
Hi. I have an error when I first started the mod: 

`
NULL pointer to instance. Variable 'className'
Class:      'CustomMission'
Function: 'EquipCharacter'
Stack trace:
d3xters-class-selection/Scripts/5_Mission/missionserver.c:380
scripts/5_Mission/mission\missionserver.c:405
JM/CF/Scripts/5_Mission/communityframework\mission\missionserver.c:122
scripts/5_Mission/mission\missionserver.c:164
JM/CF/Scripts/5_Mission/communityframework\mission\missionserver.c:18
SearchTheCorpse\scripts\5_Mission/searchthecorpse\mission\moddedmissionserver.c:7
d3xters-class-selection/Scripts/5_Mission/missionserver.c:315
scripts/3_Game/dayzgame.c:1293
`

Mods on the server are connected:

`@CF;@Community-Online-Tools;@Weapons_Pack_by_DimA;@Banking;@BaseBuildingPlus;@Bed-Respawning;@BuildAnywhere_v3;@BuilderItems;@Code_Lock;@CorpseSearching;@CustomCharacterSpawnFix;@DayZ_Class-Selection;@GearPDA;@Heroes_And_Bandits;@Trader;@Translation_Base_Building_Plus;@Unlimited_Stamina;@VanillaPlusPlusMap;@VEHICLES_DAYZ174;@USSR_Dayz_Project`

servermods `@CFDZPlugin;@My_Server_Mod`

**Comment by Irkutsk38** [comment]
> 
> 
> Hi. I have an error when I first started the mod:
> 
> `NULL pointer to instance. Variable 'className' Class: 'CustomMission' Function: 'EquipCharacter' Stack trace: d3xters-class-selection/Scripts/5_Mission/missionserver.c:380 scripts/5_Mission/mission\missionserver.c:405 JM/CF/Scripts/5_Mission/communityframework\mission\missionserver.c:122 scripts/5_Mission/mission\missionserver.c:164 JM/CF/Scripts/5_Mission/communityframework\mission\missionserver.c:18 SearchTheCorpse\scripts\5_Mission/searchthecorpse\mission\moddedmissionserver.c:7 d3xters-class-selection/Scripts/5_Mission/missionserver.c:315 scripts/3_Game/dayzgame.c:1293`
> 
> Mods on the server are connected:
> 
> `@CF;@Community-Online-Tools;@Weapons_Pack_by_DimA;@Banking;@BaseBuildingPlus;@Bed-Respawning;@BuildAnywhere_v3;@BuilderItems;@Code_Lock;@CorpseSearching;@CustomCharacterSpawnFix;@DayZ_Class-Selection;@GearPDA;@Heroes_And_Bandits;@Trader;@Translation_Base_Building_Plus;@Unlimited_Stamina;@VanillaPlusPlusMap;@VEHICLES_DAYZ174;@USSR_Dayz_Project`
> 
> servermods `@CFDZPlugin;@My_Server_Mod`

**Comment by d3xter-dev** [comment]
Will look into it when im back from work, would you please upload your classes (json files) ?

**Comment by FPS-86** [comment]
ClassDataExample.json https://pastebin.com/nYVKpqmc

**Comment by d3xter-dev** [comment]
So you didn't add any own classes yet? And you have the ClassDataExample.json in the classes folder, right? 
(Basicly a fresh install)

**Comment by FPS-86** [comment]
Yes. I just added your mod to my server and did a server update, i.e. deleted the storage_1 folder in dayzOffline.chernarusplus

**Comment by d3xter-dev** [comment]
Should be fixed!
