### ISSUE TITLE
Deagle Scope and Fal FoldingBttstck

### ISSUE THREAD

**Issue by UneveNBR** [d3xter-dev/dayz-class-selection#5]
Hi.
First, sorry for my english.
I'm having trouble adding items [deagle scope/pistolscope and Fal FoldingBttstck/OeBttstck] to the class menu.
When I add them, the preview of the items disappear from the class selection menu. This makes the choice impossible.
Any idea to solve this?
Tks

**Comment by UneveNBR** [comment]
I forgot to put the comma before other equipment.
sorry

**Comment by d3xter-dev** [comment]
Glad you figured it out!
